### ISSUE TITLE
AttributeError: module 'fitz' has no attribute 'open'

### ISSUE THREAD

**Issue by zack-emmert** [EthanJWright/pdfparse#1]
When attempting to run the script on the 5th edition Dungeon Master's Guide, I get the following result:

Command: `python3 parse.py -i "Dungeon Master's Guide.pdf" -m 8 -r h1`

Stacktrace:
```py
Traceback (most recent call last):
  File "/home/user/Downloads/DND PDFs/parse.py", line 408, in <module>
    main()
  File "/home/zack/Downloads/DND PDFs/parse.py", line 373, in main
    doc = fitz.open(input_file)
AttributeError: module 'fitz' has no attribute 'open'
```

The version of `fitz` that I have installed is `0.0.1.dev2`, the latest version on PyPi.

**Comment by ipsi** [comment]
For anyone reading this in the future, the correct package is `PyMuPDF`, e.g., `pip3 install PyMuPDF`.

**Comment by EthanJWright** [comment]
Ah shoot missed this issue - good catch, I realized I never added a requirements.txt installation script, I'll add that!
